type IntelliIconValue =
  'alert' |
  'arrow-down' |
  'arrow-left' |
  'arrow-right' |
  'arrow-up' |
  'australia' |
  'avatar' |
  'book' |
  'card' |
  'check' |
  'check-list' |
  'check-list-2' |
  'check-list-3' |
  'check-list-4' |
  'clock' |
  'coffee' |
  'column' |
  'column-tick' |
  'config' |
  'config-2' |
  'copy' |
  'cross-large' |
  'cross-small' |
  'email' |
  'glasses' |
  'glasses-2' |
  'goal-performance' |
  'heart' |
  'line-chart' |
  'location' |
  'menu-burger' |
  'mini-dialog' |
  'multi-line-chart' |
  'neutral' |
  'orgs' |
  'orgs-board' |
  'peer-task' |
  'people' |
  'people-2' |
  'people-3' |
  'phone' |
  'pie' |
  'safety-and-wellbeing' |
  'search' |
  'security' |
  'self-task' |
  'sentiment' |
  'sentiment-diary-notes' |
  'sentiment-forms' |
  'sentiment-goals' |
  'sentiment-performance-management' |
  'shield' |
  'smile' |
  'smile-round-fill' |
  'social-facebook' |
  'social-instagram' |
  'social-linkedin' |
  'social-twitter' |
  'support' |
  'survival-analytics' |
  'sync' |
  'sync-2' |
  'sync-3' |
  'sync-4' |
  'sync-5' |
  'sync-6' |
  'target' |
  'tick-small' |
  'training' |
  'upload'

export {
  IntelliIconValue
}
