declare module 'html-to-react'
declare module 'react-linkify'
declare module 'better-react-spinkit'
declare module 'foundation-sites/js/foundation.core'
declare module 'foundation-sites/js/foundation.accordionMenu'
declare module 'react-styled-flexboxgrid'
