declare module 'html-to-react'
declare module 'react-linkify'
declare module 'better-react-spinkit'
declare module 'foundation-sites'
declare module 'react-styled-flexboxgrid'
declare module 'react-string-replace'
declare module 'react-use-gesture'
declare module 'body-scroll-lock'
declare module '@intellihr/styled-components-breakpoint'
declare let Foundation: any
