FROM node:12.20.0-alpine

RUN apk upgrade &&\
    apk --update add git openssh-client

RUN rm -rf /var/cache/apk/*

ENV GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"

WORKDIR /var/task

ADD package.json /var/task
ADD yarn.lock /var/task
ADD .npmrc /var/task

RUN yarn --frozen-lockfile

ENV NODE_ICU_DATA=node_modules/full-icu

ADD . /var/task
