FROM node:12.20.0-alpine

WORKDIR /var/task

EXPOSE 6060

ADD package.json /var/task
ADD yarn.lock /var/task
ADD .npmrc /var/task

RUN yarn --frozen-lockfile && mkdir dist types

ENV NODE_ICU_DATA=node_modules/full-icu

ADD . /var/task
