version: '3'
services:
  base: &base
    build: .

  code: &code
    <<: *base
    volumes:
      - .:/code
    ports:
      - 6060:6060

  code-mac:
    <<: *code
    volumes:
      - .:/code
      - ui-components:/code/node_modules # Optimisation for Docker-Mac

  jenkins:
    <<: *base

volumes:
  ui-components: ~
