type IntelliIconPrefixedValue =
  'intelli-icon-alert' |
  'intelli-icon-arrow-down' |
  'intelli-icon-arrow-left' |
  'intelli-icon-arrow-right' |
  'intelli-icon-arrow-up' |
  'intelli-icon-australia' |
  'intelli-icon-avatar' |
  'intelli-icon-book' |
  'intelli-icon-card' |
  'intelli-icon-check' |
  'intelli-icon-check-list' |
  'intelli-icon-check-list-2' |
  'intelli-icon-check-list-3' |
  'intelli-icon-check-list-4' |
  'intelli-icon-clock' |
  'intelli-icon-coffee' |
  'intelli-icon-column' |
  'intelli-icon-column-tick' |
  'intelli-icon-config' |
  'intelli-icon-config-2' |
  'intelli-icon-copy' |
  'intelli-icon-cross-large' |
  'intelli-icon-cross-small' |
  'intelli-icon-email' |
  'intelli-icon-glasses' |
  'intelli-icon-glasses-2' |
  'intelli-icon-goal-performance' |
  'intelli-icon-heart' |
  'intelli-icon-line-chart' |
  'intelli-icon-location' |
  'intelli-icon-menu-burger' |
  'intelli-icon-mini-dialog' |
  'intelli-icon-multi-line-chart' |
  'intelli-icon-neutral' |
  'intelli-icon-orgs' |
  'intelli-icon-orgs-board' |
  'intelli-icon-peer-task' |
  'intelli-icon-people' |
  'intelli-icon-people-2' |
  'intelli-icon-people-3' |
  'intelli-icon-phone' |
  'intelli-icon-pie' |
  'intelli-icon-safety-and-wellbeing' |
  'intelli-icon-search' |
  'intelli-icon-security' |
  'intelli-icon-self-task' |
  'intelli-icon-sentiment' |
  'intelli-icon-sentiment-diary-notes' |
  'intelli-icon-sentiment-forms' |
  'intelli-icon-sentiment-goals' |
  'intelli-icon-sentiment-performance-management' |
  'intelli-icon-shield' |
  'intelli-icon-smile' |
  'intelli-icon-smile-round-fill' |
  'intelli-icon-social-facebook' |
  'intelli-icon-social-instagram' |
  'intelli-icon-social-linkedin' |
  'intelli-icon-social-twitter' |
  'intelli-icon-support' |
  'intelli-icon-survival-analytics' |
  'intelli-icon-sync' |
  'intelli-icon-sync-2' |
  'intelli-icon-sync-3' |
  'intelli-icon-sync-4' |
  'intelli-icon-sync-5' |
  'intelli-icon-sync-6' |
  'intelli-icon-target' |
  'intelli-icon-tick-small' |
  'intelli-icon-training' |
  'intelli-icon-upload'

export {
  IntelliIconPrefixedValue
}
