// Following is exported from fontawesome 4.7.0
type FontAwesomeIconType = 'fa-500px' |
  'fa-address-book' |
  'fa-address-book-o' |
  'fa-address-card' |
  'fa-address-card-o' |
  'fa-adjust' |
  'fa-adn' |
  'fa-align-center' |
  'fa-align-justify' |
  'fa-align-left' |
  'fa-align-right' |
  'fa-amazon' |
  'fa-ambulance' |
  'fa-american-sign-language-interpreting' |
  'fa-anchor' |
  'fa-android' |
  'fa-angellist' |
  'fa-angle-double-down' |
  'fa-angle-double-left' |
  'fa-angle-double-right' |
  'fa-angle-double-up' |
  'fa-angle-down' |
  'fa-angle-left' |
  'fa-angle-right' |
  'fa-angle-up' |
  'fa-apple' |
  'fa-archive' |
  'fa-area-chart' |
  'fa-arrow-circle-down' |
  'fa-arrow-circle-left' |
  'fa-arrow-circle-o-down' |
  'fa-arrow-circle-o-left' |
  'fa-arrow-circle-o-right' |
  'fa-arrow-circle-o-up' |
  'fa-arrow-circle-right' |
  'fa-arrow-circle-up' |
  'fa-arrow-down' |
  'fa-arrow-left' |
  'fa-arrow-right' |
  'fa-arrow-up' |
  'fa-arrows' |
  'fa-arrows-alt' |
  'fa-arrows-h' |
  'fa-arrows-v' |
  'fa-asl-interpreting' |
  'fa-assistive-listening-systems' |
  'fa-asterisk' |
  'fa-at' |
  'fa-audio-description' |
  'fa-automobile' |
  'fa-backward' |
  'fa-balance-scale' |
  'fa-ban' |
  'fa-bandcamp' |
  'fa-bank' |
  'fa-bar-chart' |
  'fa-bar-chart-o' |
  'fa-barcode' |
  'fa-bars' |
  'fa-bath' |
  'fa-bathtub' |
  'fa-battery' |
  'fa-battery-0' |
  'fa-battery-1' |
  'fa-battery-2' |
  'fa-battery-3' |
  'fa-battery-4' |
  'fa-battery-empty' |
  'fa-battery-full' |
  'fa-battery-half' |
  'fa-battery-quarter' |
  'fa-battery-three-quarters' |
  'fa-bed' |
  'fa-beer' |
  'fa-behance' |
  'fa-behance-square' |
  'fa-bell' |
  'fa-bell-o' |
  'fa-bell-slash' |
  'fa-bell-slash-o' |
  'fa-bicycle' |
  'fa-binoculars' |
  'fa-birthday-cake' |
  'fa-bitbucket' |
  'fa-bitbucket-square' |
  'fa-bitcoin' |
  'fa-black-tie' |
  'fa-blind' |
  'fa-bluetooth' |
  'fa-bluetooth-b' |
  'fa-bold' |
  'fa-bolt' |
  'fa-bomb' |
  'fa-book' |
  'fa-bookmark' |
  'fa-bookmark-o' |
  'fa-braille' |
  'fa-briefcase' |
  'fa-btc' |
  'fa-bug' |
  'fa-building' |
  'fa-building-o' |
  'fa-bullhorn' |
  'fa-bullseye' |
  'fa-bus' |
  'fa-buysellads' |
  'fa-cab' |
  'fa-calculator' |
  'fa-calendar' |
  'fa-calendar-check-o' |
  'fa-calendar-minus-o' |
  'fa-calendar-o' |
  'fa-calendar-plus-o' |
  'fa-calendar-times-o' |
  'fa-camera' |
  'fa-camera-retro' |
  'fa-car' |
  'fa-caret-down' |
  'fa-caret-left' |
  'fa-caret-right' |
  'fa-caret-square-o-down' |
  'fa-caret-square-o-left' |
  'fa-caret-square-o-right' |
  'fa-caret-square-o-up' |
  'fa-caret-up' |
  'fa-cart-arrow-down' |
  'fa-cart-plus' |
  'fa-cc' |
  'fa-cc-amex' |
  'fa-cc-diners-club' |
  'fa-cc-discover' |
  'fa-cc-jcb' |
  'fa-cc-mastercard' |
  'fa-cc-paypal' |
  'fa-cc-stripe' |
  'fa-cc-visa' |
  'fa-certificate' |
  'fa-chain' |
  'fa-chain-broken' |
  'fa-check' |
  'fa-check-circle' |
  'fa-check-circle-o' |
  'fa-check-square' |
  'fa-check-square-o' |
  'fa-chevron-circle-down' |
  'fa-chevron-circle-left' |
  'fa-chevron-circle-right' |
  'fa-chevron-circle-up' |
  'fa-chevron-down' |
  'fa-chevron-left' |
  'fa-chevron-right' |
  'fa-chevron-up' |
  'fa-child' |
  'fa-chrome' |
  'fa-circle' |
  'fa-circle-o' |
  'fa-circle-o-notch' |
  'fa-circle-thin' |
  'fa-clipboard' |
  'fa-clock-o' |
  'fa-clone' |
  'fa-close' |
  'fa-cloud' |
  'fa-cloud-download' |
  'fa-cloud-upload' |
  'fa-cny' |
  'fa-code' |
  'fa-code-fork' |
  'fa-codepen' |
  'fa-codiepie' |
  'fa-coffee' |
  'fa-cog' |
  'fa-cogs' |
  'fa-columns' |
  'fa-comment' |
  'fa-comment-o' |
  'fa-commenting' |
  'fa-commenting-o' |
  'fa-comments' |
  'fa-comments-o' |
  'fa-compass' |
  'fa-compress' |
  'fa-connectdevelop' |
  'fa-contao' |
  'fa-copy' |
  'fa-copyright' |
  'fa-creative-commons' |
  'fa-credit-card' |
  'fa-credit-card-alt' |
  'fa-crop' |
  'fa-crosshairs' |
  'fa-css3' |
  'fa-cube' |
  'fa-cubes' |
  'fa-cut' |
  'fa-cutlery' |
  'fa-dashboard' |
  'fa-dashcube' |
  'fa-database' |
  'fa-deaf' |
  'fa-deafness' |
  'fa-dedent' |
  'fa-delicious' |
  'fa-desktop' |
  'fa-deviantart' |
  'fa-diamond' |
  'fa-digg' |
  'fa-dollar' |
  'fa-dot-circle-o' |
  'fa-download' |
  'fa-dribbble' |
  'fa-drivers-license' |
  'fa-drivers-license-o' |
  'fa-dropbox' |
  'fa-drupal' |
  'fa-edge' |
  'fa-edit' |
  'fa-eercast' |
  'fa-eject' |
  'fa-ellipsis-h' |
  'fa-ellipsis-v' |
  'fa-empire' |
  'fa-envelope' |
  'fa-envelope-o' |
  'fa-envelope-open' |
  'fa-envelope-open-o' |
  'fa-envelope-square' |
  'fa-envira' |
  'fa-eraser' |
  'fa-etsy' |
  'fa-eur' |
  'fa-euro' |
  'fa-exchange' |
  'fa-exclamation' |
  'fa-exclamation-circle' |
  'fa-exclamation-triangle' |
  'fa-expand' |
  'fa-expeditedssl' |
  'fa-external-link' |
  'fa-external-link-square' |
  'fa-eye' |
  'fa-eye-slash' |
  'fa-eyedropper' |
  'fa-fa' |
  'fa-facebook' |
  'fa-facebook-f' |
  'fa-facebook-official' |
  'fa-facebook-square' |
  'fa-fast-backward' |
  'fa-fast-forward' |
  'fa-fax' |
  'fa-feed' |
  'fa-female' |
  'fa-fighter-jet' |
  'fa-file' |
  'fa-file-archive-o' |
  'fa-file-audio-o' |
  'fa-file-code-o' |
  'fa-file-excel-o' |
  'fa-file-image-o' |
  'fa-file-movie-o' |
  'fa-file-o' |
  'fa-file-pdf-o' |
  'fa-file-photo-o' |
  'fa-file-picture-o' |
  'fa-file-powerpoint-o' |
  'fa-file-sound-o' |
  'fa-file-text' |
  'fa-file-text-o' |
  'fa-file-video-o' |
  'fa-file-word-o' |
  'fa-file-zip-o' |
  'fa-files-o' |
  'fa-film' |
  'fa-filter' |
  'fa-fire' |
  'fa-fire-extinguisher' |
  'fa-firefox' |
  'fa-first-order' |
  'fa-flag' |
  'fa-flag-checkered' |
  'fa-flag-o' |
  'fa-flash' |
  'fa-flask' |
  'fa-flickr' |
  'fa-floppy-o' |
  'fa-folder' |
  'fa-folder-o' |
  'fa-folder-open' |
  'fa-folder-open-o' |
  'fa-font' |
  'fa-font-awesome' |
  'fa-fonticons' |
  'fa-fort-awesome' |
  'fa-forumbee' |
  'fa-forward' |
  'fa-foursquare' |
  'fa-free-code-camp' |
  'fa-frown-o' |
  'fa-futbol-o' |
  'fa-gamepad' |
  'fa-gavel' |
  'fa-gbp' |
  'fa-ge' |
  'fa-gear' |
  'fa-gears' |
  'fa-genderless' |
  'fa-get-pocket' |
  'fa-gg' |
  'fa-gg-circle' |
  'fa-gift' |
  'fa-git' |
  'fa-git-square' |
  'fa-github' |
  'fa-github-alt' |
  'fa-github-square' |
  'fa-gitlab' |
  'fa-gittip' |
  'fa-glass' |
  'fa-glide' |
  'fa-glide-g' |
  'fa-globe' |
  'fa-google' |
  'fa-google-plus' |
  'fa-google-plus-circle' |
  'fa-google-plus-official' |
  'fa-google-plus-square' |
  'fa-google-wallet' |
  'fa-graduation-cap' |
  'fa-gratipay' |
  'fa-grav' |
  'fa-group' |
  'fa-h-square' |
  'fa-hacker-news' |
  'fa-hand-grab-o' |
  'fa-hand-lizard-o' |
  'fa-hand-o-down' |
  'fa-hand-o-left' |
  'fa-hand-o-right' |
  'fa-hand-o-up' |
  'fa-hand-paper-o' |
  'fa-hand-peace-o' |
  'fa-hand-pointer-o' |
  'fa-hand-rock-o' |
  'fa-hand-scissors-o' |
  'fa-hand-spock-o' |
  'fa-hand-stop-o' |
  'fa-handshake-o' |
  'fa-hard-of-hearing' |
  'fa-hashtag' |
  'fa-hdd-o' |
  'fa-header' |
  'fa-headphones' |
  'fa-heart' |
  'fa-heart-o' |
  'fa-heartbeat' |
  'fa-history' |
  'fa-home' |
  'fa-hospital-o' |
  'fa-hotel' |
  'fa-hourglass' |
  'fa-hourglass-1' |
  'fa-hourglass-2' |
  'fa-hourglass-3' |
  'fa-hourglass-end' |
  'fa-hourglass-half' |
  'fa-hourglass-o' |
  'fa-hourglass-start' |
  'fa-houzz' |
  'fa-html5' |
  'fa-i-cursor' |
  'fa-id-badge' |
  'fa-id-card' |
  'fa-id-card-o' |
  'fa-ils' |
  'fa-image' |
  'fa-imdb' |
  'fa-inbox' |
  'fa-indent' |
  'fa-industry' |
  'fa-info' |
  'fa-info-circle' |
  'fa-inr' |
  'fa-instagram' |
  'fa-institution' |
  'fa-internet-explorer' |
  'fa-intersex' |
  'fa-ioxhost' |
  'fa-italic' |
  'fa-joomla' |
  'fa-jpy' |
  'fa-jsfiddle' |
  'fa-key' |
  'fa-keyboard-o' |
  'fa-krw' |
  'fa-language' |
  'fa-laptop' |
  'fa-lastfm' |
  'fa-lastfm-square' |
  'fa-leaf' |
  'fa-leanpub' |
  'fa-legal' |
  'fa-lemon-o' |
  'fa-level-down' |
  'fa-level-up' |
  'fa-life-bouy' |
  'fa-life-buoy' |
  'fa-life-ring' |
  'fa-life-saver' |
  'fa-lightbulb-o' |
  'fa-line-chart' |
  'fa-link' |
  'fa-linkedin' |
  'fa-linkedin-square' |
  'fa-linode' |
  'fa-linux' |
  'fa-list' |
  'fa-list-alt' |
  'fa-list-ol' |
  'fa-list-ul' |
  'fa-location-arrow' |
  'fa-lock' |
  'fa-long-arrow-down' |
  'fa-long-arrow-left' |
  'fa-long-arrow-right' |
  'fa-long-arrow-up' |
  'fa-low-vision' |
  'fa-magic' |
  'fa-magnet' |
  'fa-mail-forward' |
  'fa-mail-reply' |
  'fa-mail-reply-all' |
  'fa-male' |
  'fa-map' |
  'fa-map-marker' |
  'fa-map-o' |
  'fa-map-pin' |
  'fa-map-signs' |
  'fa-mars' |
  'fa-mars-double' |
  'fa-mars-stroke' |
  'fa-mars-stroke-h' |
  'fa-mars-stroke-v' |
  'fa-maxcdn' |
  'fa-meanpath' |
  'fa-medium' |
  'fa-medkit' |
  'fa-meetup' |
  'fa-meh-o' |
  'fa-mercury' |
  'fa-microchip' |
  'fa-microphone' |
  'fa-microphone-slash' |
  'fa-minus' |
  'fa-minus-circle' |
  'fa-minus-square' |
  'fa-minus-square-o' |
  'fa-mixcloud' |
  'fa-mobile' |
  'fa-mobile-phone' |
  'fa-modx' |
  'fa-money' |
  'fa-moon-o' |
  'fa-mortar-board' |
  'fa-motorcycle' |
  'fa-mouse-pointer' |
  'fa-music' |
  'fa-navicon' |
  'fa-neuter' |
  'fa-newspaper-o' |
  'fa-object-group' |
  'fa-object-ungroup' |
  'fa-odnoklassniki' |
  'fa-odnoklassniki-square' |
  'fa-opencart' |
  'fa-openid' |
  'fa-opera' |
  'fa-optin-monster' |
  'fa-outdent' |
  'fa-pagelines' |
  'fa-paint-brush' |
  'fa-paper-plane' |
  'fa-paper-plane-o' |
  'fa-paperclip' |
  'fa-paragraph' |
  'fa-paste' |
  'fa-pause' |
  'fa-pause-circle' |
  'fa-pause-circle-o' |
  'fa-paw' |
  'fa-paypal' |
  'fa-pencil' |
  'fa-pencil-square' |
  'fa-pencil-square-o' |
  'fa-percent' |
  'fa-phone' |
  'fa-phone-square' |
  'fa-photo' |
  'fa-picture-o' |
  'fa-pie-chart' |
  'fa-pied-piper' |
  'fa-pied-piper-alt' |
  'fa-pied-piper-pp' |
  'fa-pinterest' |
  'fa-pinterest-p' |
  'fa-pinterest-square' |
  'fa-plane' |
  'fa-play' |
  'fa-play-circle' |
  'fa-play-circle-o' |
  'fa-plug' |
  'fa-plus' |
  'fa-plus-circle' |
  'fa-plus-square' |
  'fa-plus-square-o' |
  'fa-podcast' |
  'fa-power-off' |
  'fa-print' |
  'fa-product-hunt' |
  'fa-puzzle-piece' |
  'fa-qq' |
  'fa-qrcode' |
  'fa-question' |
  'fa-question-circle' |
  'fa-question-circle-o' |
  'fa-quora' |
  'fa-quote-left' |
  'fa-quote-right' |
  'fa-ra' |
  'fa-random' |
  'fa-ravelry' |
  'fa-rebel' |
  'fa-recycle' |
  'fa-reddit' |
  'fa-reddit-alien' |
  'fa-reddit-square' |
  'fa-refresh' |
  'fa-registered' |
  'fa-remove' |
  'fa-renren' |
  'fa-reorder' |
  'fa-repeat' |
  'fa-reply' |
  'fa-reply-all' |
  'fa-resistance' |
  'fa-retweet' |
  'fa-rmb' |
  'fa-road' |
  'fa-rocket' |
  'fa-rotate-left' |
  'fa-rotate-right' |
  'fa-rouble' |
  'fa-rss' |
  'fa-rss-square' |
  'fa-rub' |
  'fa-ruble' |
  'fa-rupee' |
  'fa-s15' |
  'fa-safari' |
  'fa-save' |
  'fa-scissors' |
  'fa-scribd' |
  'fa-search' |
  'fa-search-minus' |
  'fa-search-plus' |
  'fa-sellsy' |
  'fa-send' |
  'fa-send-o' |
  'fa-server' |
  'fa-share' |
  'fa-share-alt' |
  'fa-share-alt-square' |
  'fa-share-square' |
  'fa-share-square-o' |
  'fa-shekel' |
  'fa-sheqel' |
  'fa-shield' |
  'fa-ship' |
  'fa-shirtsinbulk' |
  'fa-shopping-bag' |
  'fa-shopping-basket' |
  'fa-shopping-cart' |
  'fa-shower' |
  'fa-sign-in' |
  'fa-sign-language' |
  'fa-sign-out' |
  'fa-signal' |
  'fa-signing' |
  'fa-simplybuilt' |
  'fa-sitemap' |
  'fa-skyatlas' |
  'fa-skype' |
  'fa-slack' |
  'fa-sliders' |
  'fa-slideshare' |
  'fa-smile-o' |
  'fa-snapchat' |
  'fa-snapchat-ghost' |
  'fa-snapchat-square' |
  'fa-snowflake-o' |
  'fa-soccer-ball-o' |
  'fa-sort' |
  'fa-sort-alpha-asc' |
  'fa-sort-alpha-desc' |
  'fa-sort-amount-asc' |
  'fa-sort-amount-desc' |
  'fa-sort-asc' |
  'fa-sort-desc' |
  'fa-sort-down' |
  'fa-sort-numeric-asc' |
  'fa-sort-numeric-desc' |
  'fa-sort-up' |
  'fa-soundcloud' |
  'fa-space-shuttle' |
  'fa-spinner' |
  'fa-spoon' |
  'fa-spotify' |
  'fa-square' |
  'fa-square-o' |
  'fa-stack-exchange' |
  'fa-stack-overflow' |
  'fa-star' |
  'fa-star-half' |
  'fa-star-half-empty' |
  'fa-star-half-full' |
  'fa-star-half-o' |
  'fa-star-o' |
  'fa-steam' |
  'fa-steam-square' |
  'fa-step-backward' |
  'fa-step-forward' |
  'fa-stethoscope' |
  'fa-sticky-note' |
  'fa-sticky-note-o' |
  'fa-stop' |
  'fa-stop-circle' |
  'fa-stop-circle-o' |
  'fa-street-view' |
  'fa-strikethrough' |
  'fa-stumbleupon' |
  'fa-stumbleupon-circle' |
  'fa-subscript' |
  'fa-subway' |
  'fa-suitcase' |
  'fa-sun-o' |
  'fa-superpowers' |
  'fa-superscript' |
  'fa-support' |
  'fa-table' |
  'fa-tablet' |
  'fa-tachometer' |
  'fa-tag' |
  'fa-tags' |
  'fa-tasks' |
  'fa-taxi' |
  'fa-telegram' |
  'fa-television' |
  'fa-tencent-weibo' |
  'fa-terminal' |
  'fa-text-height' |
  'fa-text-width' |
  'fa-th' |
  'fa-th-large' |
  'fa-th-list' |
  'fa-themeisle' |
  'fa-thermometer' |
  'fa-thermometer-0' |
  'fa-thermometer-1' |
  'fa-thermometer-2' |
  'fa-thermometer-3' |
  'fa-thermometer-4' |
  'fa-thermometer-empty' |
  'fa-thermometer-full' |
  'fa-thermometer-half' |
  'fa-thermometer-quarter' |
  'fa-thermometer-three-quarters' |
  'fa-thumb-tack' |
  'fa-thumbs-down' |
  'fa-thumbs-o-down' |
  'fa-thumbs-o-up' |
  'fa-thumbs-up' |
  'fa-ticket' |
  'fa-times' |
  'fa-times-circle' |
  'fa-times-circle-o' |
  'fa-times-rectangle' |
  'fa-times-rectangle-o' |
  'fa-tint' |
  'fa-toggle-down' |
  'fa-toggle-left' |
  'fa-toggle-off' |
  'fa-toggle-on' |
  'fa-toggle-right' |
  'fa-toggle-up' |
  'fa-trademark' |
  'fa-train' |
  'fa-transgender' |
  'fa-transgender-alt' |
  'fa-trash' |
  'fa-trash-o' |
  'fa-tree' |
  'fa-trello' |
  'fa-tripadvisor' |
  'fa-trophy' |
  'fa-truck' |
  'fa-try' |
  'fa-tty' |
  'fa-tumblr' |
  'fa-tumblr-square' |
  'fa-turkish-lira' |
  'fa-tv' |
  'fa-twitch' |
  'fa-twitter' |
  'fa-twitter-square' |
  'fa-umbrella' |
  'fa-underline' |
  'fa-undo' |
  'fa-universal-access' |
  'fa-university' |
  'fa-unlink' |
  'fa-unlock' |
  'fa-unlock-alt' |
  'fa-unsorted' |
  'fa-upload' |
  'fa-usb' |
  'fa-usd' |
  'fa-user' |
  'fa-user-circle' |
  'fa-user-circle-o' |
  'fa-user-md' |
  'fa-user-o' |
  'fa-user-plus' |
  'fa-user-secret' |
  'fa-user-times' |
  'fa-users' |
  'fa-vcard' |
  'fa-vcard-o' |
  'fa-venus' |
  'fa-venus-double' |
  'fa-venus-mars' |
  'fa-viacoin' |
  'fa-viadeo' |
  'fa-viadeo-square' |
  'fa-video-camera' |
  'fa-vimeo' |
  'fa-vimeo-square' |
  'fa-vine' |
  'fa-vk' |
  'fa-volume-control-phone' |
  'fa-volume-down' |
  'fa-volume-off' |
  'fa-volume-up' |
  'fa-warning' |
  'fa-wechat' |
  'fa-weibo' |
  'fa-weixin' |
  'fa-whatsapp' |
  'fa-wheelchair' |
  'fa-wheelchair-alt' |
  'fa-wifi' |
  'fa-wikipedia-w' |
  'fa-window-close' |
  'fa-window-close-o' |
  'fa-window-maximize' |
  'fa-window-minimize' |
  'fa-window-restore' |
  'fa-windows' |
  'fa-won' |
  'fa-wordpress' |
  'fa-wpbeginner' |
  'fa-wpexplorer' |
  'fa-wpforms' |
  'fa-wrench' |
  'fa-xing' |
  'fa-xing-square' |
  'fa-y-combinator' |
  'fa-y-combinator-square' |
  'fa-yahoo' |
  'fa-yc' |
  'fa-yc-square' |
  'fa-yelp' |
  'fa-yen' |
  'fa-yoast' |
  'fa-youtube' |
  'fa-youtube-play' |
  'fa-youtube-square'

type FontAwesomeIconTypeNoPrefix = '500px' |
  'address-book' |
  'address-book-o' |
  'address-card' |
  'address-card-o' |
  'adjust' |
  'adn' |
  'align-center' |
  'align-justify' |
  'align-left' |
  'align-right' |
  'amazon' |
  'ambulance' |
  'american-sign-language-interpreting' |
  'anchor' |
  'android' |
  'angellist' |
  'angle-double-down' |
  'angle-double-left' |
  'angle-double-right' |
  'angle-double-up' |
  'angle-down' |
  'angle-left' |
  'angle-right' |
  'angle-up' |
  'apple' |
  'archive' |
  'area-chart' |
  'arrow-circle-down' |
  'arrow-circle-left' |
  'arrow-circle-o-down' |
  'arrow-circle-o-left' |
  'arrow-circle-o-right' |
  'arrow-circle-o-up' |
  'arrow-circle-right' |
  'arrow-circle-up' |
  'arrow-down' |
  'arrow-left' |
  'arrow-right' |
  'arrow-up' |
  'arrows' |
  'arrows-alt' |
  'arrows-h' |
  'arrows-v' |
  'asl-interpreting' |
  'assistive-listening-systems' |
  'asterisk' |
  'at' |
  'audio-description' |
  'automobile' |
  'backward' |
  'balance-scale' |
  'ban' |
  'bandcamp' |
  'bank' |
  'bar-chart' |
  'bar-chart-o' |
  'barcode' |
  'bars' |
  'bath' |
  'bathtub' |
  'battery' |
  'battery-0' |
  'battery-1' |
  'battery-2' |
  'battery-3' |
  'battery-4' |
  'battery-empty' |
  'battery-full' |
  'battery-half' |
  'battery-quarter' |
  'battery-three-quarters' |
  'bed' |
  'beer' |
  'behance' |
  'behance-square' |
  'bell' |
  'bell-o' |
  'bell-slash' |
  'bell-slash-o' |
  'bicycle' |
  'binoculars' |
  'birthday-cake' |
  'bitbucket' |
  'bitbucket-square' |
  'bitcoin' |
  'black-tie' |
  'blind' |
  'bluetooth' |
  'bluetooth-b' |
  'bold' |
  'bolt' |
  'bomb' |
  'book' |
  'bookmark' |
  'bookmark-o' |
  'braille' |
  'briefcase' |
  'btc' |
  'bug' |
  'building' |
  'building-o' |
  'bullhorn' |
  'bullseye' |
  'bus' |
  'buysellads' |
  'cab' |
  'calculator' |
  'calendar' |
  'calendar-check-o' |
  'calendar-minus-o' |
  'calendar-o' |
  'calendar-plus-o' |
  'calendar-times-o' |
  'camera' |
  'camera-retro' |
  'car' |
  'caret-down' |
  'caret-left' |
  'caret-right' |
  'caret-square-o-down' |
  'caret-square-o-left' |
  'caret-square-o-right' |
  'caret-square-o-up' |
  'caret-up' |
  'cart-arrow-down' |
  'cart-plus' |
  'cc' |
  'cc-amex' |
  'cc-diners-club' |
  'cc-discover' |
  'cc-jcb' |
  'cc-mastercard' |
  'cc-paypal' |
  'cc-stripe' |
  'cc-visa' |
  'certificate' |
  'chain' |
  'chain-broken' |
  'check' |
  'check-circle' |
  'check-circle-o' |
  'check-square' |
  'check-square-o' |
  'chevron-circle-down' |
  'chevron-circle-left' |
  'chevron-circle-right' |
  'chevron-circle-up' |
  'chevron-down' |
  'chevron-left' |
  'chevron-right' |
  'chevron-up' |
  'child' |
  'chrome' |
  'circle' |
  'circle-o' |
  'circle-o-notch' |
  'circle-thin' |
  'clipboard' |
  'clock-o' |
  'clone' |
  'close' |
  'cloud' |
  'cloud-download' |
  'cloud-upload' |
  'cny' |
  'code' |
  'code-fork' |
  'codepen' |
  'codiepie' |
  'coffee' |
  'cog' |
  'cogs' |
  'columns' |
  'comment' |
  'comment-o' |
  'commenting' |
  'commenting-o' |
  'comments' |
  'comments-o' |
  'compass' |
  'compress' |
  'connectdevelop' |
  'contao' |
  'copy' |
  'copyright' |
  'creative-commons' |
  'credit-card' |
  'credit-card-alt' |
  'crop' |
  'crosshairs' |
  'css3' |
  'cube' |
  'cubes' |
  'cut' |
  'cutlery' |
  'dashboard' |
  'dashcube' |
  'database' |
  'deaf' |
  'deafness' |
  'dedent' |
  'delicious' |
  'desktop' |
  'deviantart' |
  'diamond' |
  'digg' |
  'dollar' |
  'dot-circle-o' |
  'download' |
  'dribbble' |
  'drivers-license' |
  'drivers-license-o' |
  'dropbox' |
  'drupal' |
  'edge' |
  'edit' |
  'eercast' |
  'eject' |
  'ellipsis-h' |
  'ellipsis-v' |
  'empire' |
  'envelope' |
  'envelope-o' |
  'envelope-open' |
  'envelope-open-o' |
  'envelope-square' |
  'envira' |
  'eraser' |
  'etsy' |
  'eur' |
  'euro' |
  'exchange' |
  'exclamation' |
  'exclamation-circle' |
  'exclamation-triangle' |
  'expand' |
  'expeditedssl' |
  'external-link' |
  'external-link-square' |
  'eye' |
  'eye-slash' |
  'eyedropper' |
  'fa' |
  'facebook' |
  'facebook-f' |
  'facebook-official' |
  'facebook-square' |
  'fast-backward' |
  'fast-forward' |
  'fax' |
  'feed' |
  'female' |
  'fighter-jet' |
  'file' |
  'file-archive-o' |
  'file-audio-o' |
  'file-code-o' |
  'file-excel-o' |
  'file-image-o' |
  'file-movie-o' |
  'file-o' |
  'file-pdf-o' |
  'file-photo-o' |
  'file-picture-o' |
  'file-powerpoint-o' |
  'file-sound-o' |
  'file-text' |
  'file-text-o' |
  'file-video-o' |
  'file-word-o' |
  'file-zip-o' |
  'files-o' |
  'film' |
  'filter' |
  'fire' |
  'fire-extinguisher' |
  'firefox' |
  'first-order' |
  'flag' |
  'flag-checkered' |
  'flag-o' |
  'flash' |
  'flask' |
  'flickr' |
  'floppy-o' |
  'folder' |
  'folder-o' |
  'folder-open' |
  'folder-open-o' |
  'font' |
  'font-awesome' |
  'fonticons' |
  'fort-awesome' |
  'forumbee' |
  'forward' |
  'foursquare' |
  'free-code-camp' |
  'frown-o' |
  'futbol-o' |
  'gamepad' |
  'gavel' |
  'gbp' |
  'ge' |
  'gear' |
  'gears' |
  'genderless' |
  'get-pocket' |
  'gg' |
  'gg-circle' |
  'gift' |
  'git' |
  'git-square' |
  'github' |
  'github-alt' |
  'github-square' |
  'gitlab' |
  'gittip' |
  'glass' |
  'glide' |
  'glide-g' |
  'globe' |
  'google' |
  'google-plus' |
  'google-plus-circle' |
  'google-plus-official' |
  'google-plus-square' |
  'google-wallet' |
  'graduation-cap' |
  'gratipay' |
  'grav' |
  'group' |
  'h-square' |
  'hacker-news' |
  'hand-grab-o' |
  'hand-lizard-o' |
  'hand-o-down' |
  'hand-o-left' |
  'hand-o-right' |
  'hand-o-up' |
  'hand-paper-o' |
  'hand-peace-o' |
  'hand-pointer-o' |
  'hand-rock-o' |
  'hand-scissors-o' |
  'hand-spock-o' |
  'hand-stop-o' |
  'handshake-o' |
  'hard-of-hearing' |
  'hashtag' |
  'hdd-o' |
  'header' |
  'headphones' |
  'heart' |
  'heart-o' |
  'heartbeat' |
  'history' |
  'home' |
  'hospital-o' |
  'hotel' |
  'hourglass' |
  'hourglass-1' |
  'hourglass-2' |
  'hourglass-3' |
  'hourglass-end' |
  'hourglass-half' |
  'hourglass-o' |
  'hourglass-start' |
  'houzz' |
  'html5' |
  'i-cursor' |
  'id-badge' |
  'id-card' |
  'id-card-o' |
  'ils' |
  'image' |
  'imdb' |
  'inbox' |
  'indent' |
  'industry' |
  'info' |
  'info-circle' |
  'inr' |
  'instagram' |
  'institution' |
  'internet-explorer' |
  'intersex' |
  'ioxhost' |
  'italic' |
  'joomla' |
  'jpy' |
  'jsfiddle' |
  'key' |
  'keyboard-o' |
  'krw' |
  'language' |
  'laptop' |
  'lastfm' |
  'lastfm-square' |
  'leaf' |
  'leanpub' |
  'legal' |
  'lemon-o' |
  'level-down' |
  'level-up' |
  'life-bouy' |
  'life-buoy' |
  'life-ring' |
  'life-saver' |
  'lightbulb-o' |
  'line-chart' |
  'link' |
  'linkedin' |
  'linkedin-square' |
  'linode' |
  'linux' |
  'list' |
  'list-alt' |
  'list-ol' |
  'list-ul' |
  'location-arrow' |
  'lock' |
  'long-arrow-down' |
  'long-arrow-left' |
  'long-arrow-right' |
  'long-arrow-up' |
  'low-vision' |
  'magic' |
  'magnet' |
  'mail-forward' |
  'mail-reply' |
  'mail-reply-all' |
  'male' |
  'map' |
  'map-marker' |
  'map-o' |
  'map-pin' |
  'map-signs' |
  'mars' |
  'mars-double' |
  'mars-stroke' |
  'mars-stroke-h' |
  'mars-stroke-v' |
  'maxcdn' |
  'meanpath' |
  'medium' |
  'medkit' |
  'meetup' |
  'meh-o' |
  'mercury' |
  'microchip' |
  'microphone' |
  'microphone-slash' |
  'minus' |
  'minus-circle' |
  'minus-square' |
  'minus-square-o' |
  'mixcloud' |
  'mobile' |
  'mobile-phone' |
  'modx' |
  'money' |
  'moon-o' |
  'mortar-board' |
  'motorcycle' |
  'mouse-pointer' |
  'music' |
  'navicon' |
  'neuter' |
  'newspaper-o' |
  'object-group' |
  'object-ungroup' |
  'odnoklassniki' |
  'odnoklassniki-square' |
  'opencart' |
  'openid' |
  'opera' |
  'optin-monster' |
  'outdent' |
  'pagelines' |
  'paint-brush' |
  'paper-plane' |
  'paper-plane-o' |
  'paperclip' |
  'paragraph' |
  'paste' |
  'pause' |
  'pause-circle' |
  'pause-circle-o' |
  'paw' |
  'paypal' |
  'pencil' |
  'pencil-square' |
  'pencil-square-o' |
  'percent' |
  'phone' |
  'phone-square' |
  'photo' |
  'picture-o' |
  'pie-chart' |
  'pied-piper' |
  'pied-piper-alt' |
  'pied-piper-pp' |
  'pinterest' |
  'pinterest-p' |
  'pinterest-square' |
  'plane' |
  'play' |
  'play-circle' |
  'play-circle-o' |
  'plug' |
  'plus' |
  'plus-circle' |
  'plus-square' |
  'plus-square-o' |
  'podcast' |
  'power-off' |
  'print' |
  'product-hunt' |
  'puzzle-piece' |
  'qq' |
  'qrcode' |
  'question' |
  'question-circle' |
  'question-circle-o' |
  'quora' |
  'quote-left' |
  'quote-right' |
  'ra' |
  'random' |
  'ravelry' |
  'rebel' |
  'recycle' |
  'reddit' |
  'reddit-alien' |
  'reddit-square' |
  'refresh' |
  'registered' |
  'remove' |
  'renren' |
  'reorder' |
  'repeat' |
  'reply' |
  'reply-all' |
  'resistance' |
  'retweet' |
  'rmb' |
  'road' |
  'rocket' |
  'rotate-left' |
  'rotate-right' |
  'rouble' |
  'rss' |
  'rss-square' |
  'rub' |
  'ruble' |
  'rupee' |
  's15' |
  'safari' |
  'save' |
  'scissors' |
  'scribd' |
  'search' |
  'search-minus' |
  'search-plus' |
  'sellsy' |
  'send' |
  'send-o' |
  'server' |
  'share' |
  'share-alt' |
  'share-alt-square' |
  'share-square' |
  'share-square-o' |
  'shekel' |
  'sheqel' |
  'shield' |
  'ship' |
  'shirtsinbulk' |
  'shopping-bag' |
  'shopping-basket' |
  'shopping-cart' |
  'shower' |
  'sign-in' |
  'sign-language' |
  'sign-out' |
  'signal' |
  'signing' |
  'simplybuilt' |
  'sitemap' |
  'skyatlas' |
  'skype' |
  'slack' |
  'sliders' |
  'slideshare' |
  'smile-o' |
  'snapchat' |
  'snapchat-ghost' |
  'snapchat-square' |
  'snowflake-o' |
  'soccer-ball-o' |
  'sort' |
  'sort-alpha-asc' |
  'sort-alpha-desc' |
  'sort-amount-asc' |
  'sort-amount-desc' |
  'sort-asc' |
  'sort-desc' |
  'sort-down' |
  'sort-numeric-asc' |
  'sort-numeric-desc' |
  'sort-up' |
  'soundcloud' |
  'space-shuttle' |
  'spinner' |
  'spoon' |
  'spotify' |
  'square' |
  'square-o' |
  'stack-exchange' |
  'stack-overflow' |
  'star' |
  'star-half' |
  'star-half-empty' |
  'star-half-full' |
  'star-half-o' |
  'star-o' |
  'steam' |
  'steam-square' |
  'step-backward' |
  'step-forward' |
  'stethoscope' |
  'sticky-note' |
  'sticky-note-o' |
  'stop' |
  'stop-circle' |
  'stop-circle-o' |
  'street-view' |
  'strikethrough' |
  'stumbleupon' |
  'stumbleupon-circle' |
  'subscript' |
  'subway' |
  'suitcase' |
  'sun-o' |
  'superpowers' |
  'superscript' |
  'support' |
  'table' |
  'tablet' |
  'tachometer' |
  'tag' |
  'tags' |
  'tasks' |
  'taxi' |
  'telegram' |
  'television' |
  'tencent-weibo' |
  'terminal' |
  'text-height' |
  'text-width' |
  'th' |
  'th-large' |
  'th-list' |
  'themeisle' |
  'thermometer' |
  'thermometer-0' |
  'thermometer-1' |
  'thermometer-2' |
  'thermometer-3' |
  'thermometer-4' |
  'thermometer-empty' |
  'thermometer-full' |
  'thermometer-half' |
  'thermometer-quarter' |
  'thermometer-three-quarters' |
  'thumb-tack' |
  'thumbs-down' |
  'thumbs-o-down' |
  'thumbs-o-up' |
  'thumbs-up' |
  'ticket' |
  'times' |
  'times-circle' |
  'times-circle-o' |
  'times-rectangle' |
  'times-rectangle-o' |
  'tint' |
  'toggle-down' |
  'toggle-left' |
  'toggle-off' |
  'toggle-on' |
  'toggle-right' |
  'toggle-up' |
  'trademark' |
  'train' |
  'transgender' |
  'transgender-alt' |
  'trash' |
  'trash-o' |
  'tree' |
  'trello' |
  'tripadvisor' |
  'trophy' |
  'truck' |
  'try' |
  'tty' |
  'tumblr' |
  'tumblr-square' |
  'turkish-lira' |
  'tv' |
  'twitch' |
  'twitter' |
  'twitter-square' |
  'umbrella' |
  'underline' |
  'undo' |
  'universal-access' |
  'university' |
  'unlink' |
  'unlock' |
  'unlock-alt' |
  'unsorted' |
  'upload' |
  'usb' |
  'usd' |
  'user' |
  'user-circle' |
  'user-circle-o' |
  'user-md' |
  'user-o' |
  'user-plus' |
  'user-secret' |
  'user-times' |
  'users' |
  'vcard' |
  'vcard-o' |
  'venus' |
  'venus-double' |
  'venus-mars' |
  'viacoin' |
  'viadeo' |
  'viadeo-square' |
  'video-camera' |
  'vimeo' |
  'vimeo-square' |
  'vine' |
  'vk' |
  'volume-control-phone' |
  'volume-down' |
  'volume-off' |
  'volume-up' |
  'warning' |
  'wechat' |
  'weibo' |
  'weixin' |
  'whatsapp' |
  'wheelchair' |
  'wheelchair-alt' |
  'wifi' |
  'wikipedia-w' |
  'window-close' |
  'window-close-o' |
  'window-maximize' |
  'window-minimize' |
  'window-restore' |
  'windows' |
  'won' |
  'wordpress' |
  'wpbeginner' |
  'wpexplorer' |
  'wpforms' |
  'wrench' |
  'xing' |
  'xing-square' |
  'y-combinator' |
  'y-combinator-square' |
  'yahoo' |
  'yc' |
  'yc-square' |
  'yelp' |
  'yen' |
  'yoast' |
  'youtube' |
  'youtube-play' |
  'youtube-square'

type IntelliIconType = 'intelli-icon-alert' |
  'intelli-icon-arrow-down' |
  'intelli-icon-arrow-left' |
  'intelli-icon-arrow-right' |
  'intelli-icon-arrow-up' |
  'intelli-icon-australia' |
  'intelli-icon-avatar' |
  'intelli-icon-book' |
  'intelli-icon-card' |
  'intelli-icon-check' |
  'intelli-icon-check-list' |
  'intelli-icon-check-list-2' |
  'intelli-icon-check-list-3' |
  'intelli-icon-check-list-4' |
  'intelli-icon-clock' |
  'intelli-icon-coffee' |
  'intelli-icon-column' |
  'intelli-icon-column-tick' |
  'intelli-icon-config' |
  'intelli-icon-config-2' |
  'intelli-icon-copy' |
  'intelli-icon-cross-large' |
  'intelli-icon-cross-small' |
  'intelli-icon-email' |
  'intelli-icon-glasses' |
  'intelli-icon-glasses-2' |
  'intelli-icon-goal-performance' |
  'intelli-icon-heart' |
  'intelli-icon-line-chart' |
  'intelli-icon-location' |
  'intelli-icon-menu-burger' |
  'intelli-icon-mini-dialog' |
  'intelli-icon-multi-line-chart' |
  'intelli-icon-neutral' |
  'intelli-icon-orgs' |
  'intelli-icon-orgs-board' |
  'intelli-icon-peer-task' |
  'intelli-icon-people' |
  'intelli-icon-people-2' |
  'intelli-icon-people-3' |
  'intelli-icon-phone' |
  'intelli-icon-pie' |
  'intelli-icon-safety-and-wellbeing' |
  'intelli-icon-search' |
  'intelli-icon-security' |
  'intelli-icon-self-task' |
  'intelli-icon-sentiment' |
  'intelli-icon-sentiment-diary-notes' |
  'intelli-icon-sentiment-forms' |
  'intelli-icon-sentiment-goals' |
  'intelli-icon-sentiment-performance-management' |
  'intelli-icon-shield' |
  'intelli-icon-smile' |
  'intelli-icon-smile-round-fill' |
  'intelli-icon-social-facebook' |
  'intelli-icon-social-instagram' |
  'intelli-icon-social-linkedin' |
  'intelli-icon-social-twitter' |
  'intelli-icon-support' |
  'intelli-icon-survival-analytics' |
  'intelli-icon-sync' |
  'intelli-icon-sync-2' |
  'intelli-icon-sync-3' |
  'intelli-icon-sync-4' |
  'intelli-icon-sync-5' |
  'intelli-icon-sync-6' |
  'intelli-icon-target' |
  'intelli-icon-tick-small' |
  'intelli-icon-training' |
  'intelli-icon-upload'

type IntelliIconTypeNoPrefix = 'alert' |
  'arrow-down' |
  'arrow-left' |
  'arrow-right' |
  'arrow-up' |
  'australia' |
  'avatar' |
  'book' |
  'card' |
  'check' |
  'check-list' |
  'check-list-2' |
  'check-list-3' |
  'check-list-4' |
  'clock' |
  'coffee' |
  'column' |
  'column-tick' |
  'config' |
  'config-2' |
  'copy' |
  'cross-large' |
  'cross-small' |
  'email' |
  'glasses' |
  'glasses-2' |
  'goal-performance' |
  'heart' |
  'line-chart' |
  'location' |
  'menu-burger' |
  'mini-dialog' |
  'multi-line-chart' |
  'neutral' |
  'orgs' |
  'orgs-board' |
  'peer-task' |
  'people' |
  'people-2' |
  'people-3' |
  'phone' |
  'pie' |
  'safety-and-wellbeing' |
  'search' |
  'security' |
  'self-task' |
  'sentiment' |
  'sentiment-diary-notes' |
  'sentiment-forms' |
  'sentiment-goals' |
  'sentiment-performance-management' |
  'shield' |
  'smile' |
  'smile-round-fill' |
  'social-facebook' |
  'social-instagram' |
  'social-linkedin' |
  'social-twitter' |
  'support' |
  'survival-analytics' |
  'sync' |
  'sync-2' |
  'sync-3' |
  'sync-4' |
  'sync-5' |
  'sync-6' |
  'target' |
  'tick-small' |
  'training' |
  'upload'

type IconType = FontAwesomeIconType | IntelliIconType

export {
  FontAwesomeIconType,
  FontAwesomeIconTypeNoPrefix,
  IntelliIconType,
  IntelliIconTypeNoPrefix,
  IconType
}
