type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

// Workaround for types files not being generated by awesome-typescript-loader
const workaround = 'workaround'

export {
  Omit,
  workaround
}
